language: perl
sudo: false
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
install:
  - cpanm --notest Minilla Test::CPAN::Meta Test::Pod Test::MinimumVersion::Fast Test::PAUSE::Permissions Test::Spellunker
  - cpanm --quiet --with-develop --installdeps --notest .
script:
  - minil test --all
